name: CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Run build
        run: gradle build
      
      - name: Run echo
        run: echo Build completed          
