name: CI

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest    
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
    steps:      
      - name: Login to docker.io        
        run:  echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      
      - uses: actions/checkout@v2
      
      
      - name: Run build
        run: gradle build
      
      - name: Run echo
        run: echo Build completed          
